---
title: "Developing Data Products - plotly"
author: "Kevin E. D'Elia"
date: "November 7, 2016"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

### Number of phones by Continent/Geographic Areas in the World

This is an interactive map created using the [plotly](https://plot.ly/r/) package.  It shows a statistical summary via a box plot of the number of phones in existence across world geographic areas.  Data was obtained from the **WorldPhones** dataset available in R.

```{r}
wf <- as.data.frame(WorldPhones)
suppressMessages(library("plotly"))
suppressMessages(library("tidyr"))
suppressMessages(library("magrittr"))
z <- gather(wf, key, country)

plot_ly(z,
             type = "box",        
             x = ~country,        
             color = ~key         
) %>%

  layout(                        
         title = "Phones by Continent", 
         xaxis = list(           
            title = "Count",     
            showgrid = F))     

```

